### ISSUE TITLE
Add support of CSS style on [source]

### ISSUE THREAD

**Issue by hasalex** [asciidoctor/asciidoctor-bespoke#17]
I would like to add styles on source code elements, for example to add margin or decrease font size.

If I add a style like this, it's not in the generated HTML.

```
[source.small, java]
----
  ...
----
```

**Comment by mojavelinux** [comment]
I agree. This appears to be an oversight.

What I've decided to do is if the role is set, add it to the class attribute of the pre element. If the block has a title, also add the role to the enclosing figure element. I add it in both places to avoid having to jump immediately to using complex selector. However, you will need to qualify the selector as `pre.myrole` instead of just `.myrole` or else you risk styling the enclosing figure element when the block has a title.

**Comment by mojavelinux** [comment]
Does that solution work for you?

**Comment by hasalex** [comment]
That's what I was looking for.
Thank you.
